SHELL := /bin/bash

COMPOSE := docker compose
BACKEND_DIR := backend
FRONTEND_DIR := frontend
SOLUTION := StayFlowCloud.sln

.DEFAULT_GOAL := help

.PHONY: help up down restart logs ps migrate seed fresh demo-reset smoke-staging build build-backend test test-backend test-frontend lint typecheck frontend-build docker-build clean nuke

help: ## Show available commands
	@awk 'BEGIN {FS = ":.*##"; printf "StayFlow Cloud commands:\n\n"} /^[a-zA-Z0-9_-]+:.*##/ {printf "  %-18s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

up: ## Build and start the full local stack
	$(COMPOSE) up --build

down: ## Stop the local stack
	$(COMPOSE) down

restart: down up ## Rebuild and restart the full local stack

logs: ## Follow service logs
	$(COMPOSE) logs -f

ps: ## Show running Compose services
	$(COMPOSE) ps

migrate: ## Run EF migrations through the one-shot migration container
	$(COMPOSE) run --rm --entrypoint dotnet migrate StayFlow.MigrationHost.dll migrate

seed: ## Seed demo tenant, roles, clients and sample inventory
	$(COMPOSE) run --rm --entrypoint dotnet migrate StayFlow.MigrationHost.dll seed

fresh: ## Reset, migrate and seed the local database from scratch
	$(COMPOSE) run --rm --entrypoint dotnet migrate StayFlow.MigrationHost.dll fresh

demo-reset: ## Reset local demo data and start the full stack from scratch
	$(COMPOSE) down -v --remove-orphans
	$(COMPOSE) up --build

smoke-staging: ## Run staging smoke checks (requires STAGING_API_URL and smoke client env vars)
	bash scripts/staging-smoke.sh

build: ## Build backend and frontend locally
	$(MAKE) build-backend
	$(MAKE) frontend-build

build-backend: ## Build the .NET solution
	dotnet build $(BACKEND_DIR)/$(SOLUTION) --configuration Release

test: ## Run backend and frontend tests
	$(MAKE) test-backend
	$(MAKE) test-frontend

test-backend: ## Run .NET tests
	dotnet test $(BACKEND_DIR)/$(SOLUTION) --configuration Release

test-frontend: ## Run frontend unit tests
	npm test --prefix $(FRONTEND_DIR)

lint: ## Run frontend lint
	npm run lint --prefix $(FRONTEND_DIR)

typecheck: ## Run frontend TypeScript checks
	npm run typecheck --prefix $(FRONTEND_DIR)

frontend-build: ## Build the Next.js app
	npm run build --prefix $(FRONTEND_DIR)

docker-build: ## Build application Docker images without starting the stack
	docker build -f $(BACKEND_DIR)/StayFlow.Api/Dockerfile -t stayflow-api:local $(BACKEND_DIR)
	docker build -f $(BACKEND_DIR)/StayFlow.NotificationService/Dockerfile -t stayflow-notification-service:local $(BACKEND_DIR)
	docker build -f $(BACKEND_DIR)/StayFlow.MigrationHost/Dockerfile -t stayflow-migration-host:local $(BACKEND_DIR)
	docker build --build-arg NEXT_PUBLIC_SITE_URL=http://localhost:3000 --build-arg NEXT_PUBLIC_OIDC_AUTHORITY=http://localhost:8080 -t stayflow-web:local $(FRONTEND_DIR)

clean: ## Stop services and remove build artifacts generated by Compose
	$(COMPOSE) down --remove-orphans

nuke: ## Stop services and delete local Docker volumes/data
	$(COMPOSE) down -v --remove-orphans
