using MediatR;
using Microsoft.EntityFrameworkCore;
using StayFlow.Application.Common.Abstractions;
using StayFlow.Domain.Billing;
using StayFlow.Domain.Guests;
using StayFlow.Domain.Reservations;
using StayFlow.Domain.Rooms;
using StayFlow.Domain.Services;

namespace StayFlow.Application.Features.Demo;

public sealed record RunSampleStayCommand : IRequest<SampleStayDto>;

public sealed record SampleStayDto(
    Guid GuestId,
    Guid RoomId,
    Guid ReservationId,
    Guid ServiceItemId,
    Guid ChargeId,
    Guid InvoiceId,
    string ConfirmationCode,
    string InvoiceNumber,
    decimal InvoiceTotal);

public sealed class RunSampleStayHandler(
    IApplicationDbContext dbContext,
    IDateTimeProvider clock,
    ITenantProvider tenantProvider) : IRequestHandler<RunSampleStayCommand, SampleStayDto>
{
    public async Task<SampleStayDto> Handle(RunSampleStayCommand request, CancellationToken cancellationToken)
    {
        var today = DateOnly.FromDateTime(clock.UtcNow.UtcDateTime);
        var checkOut = today.AddDays(1);

        var room = await GetOrCreateSampleRoom(cancellationToken);
        var service = await GetOrCreateSampleService(cancellationToken);
        var guest = Guest.Create("Avery", "Sample", $"sample-{Guid.NewGuid():N}@stayflow.local", "+1 555 0100", "SAMPLE-STAY");
        var reservation = Reservation.Create(room.Id, guest.Id, DateRange.Create(today, checkOut), 1, room.BasePrice);
        reservation.Confirm();
        reservation.CheckIn();
        room.MarkOccupied();

        var charge = ReservationCharge.Create(reservation.Id, service, 1);

        var currency = await dbContext.Tenants
            .Where(t => tenantProvider.TenantId.HasValue && t.Id == tenantProvider.TenantId.Value)
            .Select(t => t.DefaultCurrency)
            .FirstOrDefaultAsync(cancellationToken) ?? "USD";
        var invoice = Invoice.Create(
            reservation.Id,
            $"INV-{clock.UtcNow:yyyyMMdd}-{Guid.NewGuid().ToString("N")[..6].ToUpperInvariant()}",
            currency,
            0.10m);
        invoice.AddLine(LineItemKind.Accommodation, "Sample stay accommodation (1 night)", 1, reservation.TotalPrice);
        invoice.AddLine(LineItemKind.Service, charge.Description, charge.Quantity, charge.UnitPrice);
        invoice.ApplyTax();
        invoice.Issue(clock.UtcNow);
        invoice.MarkPaid(clock.UtcNow);

        reservation.CheckOut();
        room.ReturnToService();
        room.UpdateCleaningStatus(RoomCleaningStatus.Dirty);

        dbContext.Guests.Add(guest);
        dbContext.Reservations.Add(reservation);
        dbContext.ReservationCharges.Add(charge);
        dbContext.Invoices.Add(invoice);
        await dbContext.SaveChangesAsync(cancellationToken);

        return new SampleStayDto(
            guest.Id,
            room.Id,
            reservation.Id,
            service.Id,
            charge.Id,
            invoice.Id,
            reservation.ConfirmationCode,
            invoice.Number,
            invoice.Total);
    }

    private async Task<Room> GetOrCreateSampleRoom(CancellationToken cancellationToken)
    {
        var availableRoom = await dbContext.Rooms
            .Where(room => room.Status == RoomStatus.Available)
            .OrderBy(room => room.Number)
            .FirstOrDefaultAsync(cancellationToken);
        if (availableRoom is not null)
        {
            return availableRoom;
        }

        var roomType = await dbContext.RoomTypes.OrderBy(roomType => roomType.Name).FirstOrDefaultAsync(cancellationToken);
        if (roomType is null)
        {
            roomType = RoomType.Create("Sample Standard", 129m, 2, "Generated by Run Sample Stay.");
            dbContext.RoomTypes.Add(roomType);
        }

        var room = Room.Create($"S{Random.Shared.Next(100, 999)}", roomType.Id, roomType.BaseRate, roomType.MaxOccupancy, 1);
        dbContext.Rooms.Add(room);
        return room;
    }

    private async Task<ServiceItem> GetOrCreateSampleService(CancellationToken cancellationToken)
    {
        var service = await dbContext.ServiceItems
            .Where(item => item.IsActive)
            .OrderBy(item => item.Name)
            .FirstOrDefaultAsync(cancellationToken);
        if (service is not null)
        {
            return service;
        }

        service = ServiceItem.Create("Welcome Dinner", 42m, ServiceCategory.FoodAndBeverage, "Generated by Run Sample Stay.");
        dbContext.ServiceItems.Add(service);
        return service;
    }
}
